version: '3'

services:

  simple:
    environment:
      - NODE_ENV=development
    build:
      context: ./
      dockerfile: Dockerfile_local
    container_name: blurer
    volumes:
      - ./:/app
    networks:
      - default
    ports:
      - "6969:6969"
      
    command: /bin/sh -c 'yarn install && yarn serve'